### ISSUE TITLE
Cannot read property 'levels' of undefined - Winston during yarn jest

### ISSUE THREAD

**Issue by sateesh2020** [notifme/notifme-sdk#80]
I have a project setup with typescript, jest and using notifme-sdk for notifications. 

Running `yarn jest` command is giving below error. 

```log
TypeError: Cannot read property 'levels' of undefined
    at Object.patchedCreate [as createLogger] (D:\workspace\iq\app\node_modules\diagnostic-channel-publishers\dist\src\winston.pub.js:110:35)
    at new Logger (D:\workspace\iq\app\node_modules\notifme-sdk\lib\util\logger.js:25:42)
    at Object.<anonymous> (D:\workspace\iq\app\node_modules\notifme-sdk\lib\util\logger.js:65:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (D:\workspace\iq\app\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at newLoader (D:\workspace\iq\app\node_modules\pirates\lib\index.js:104:7)
    at Object.newLoader [as .js] (D:\workspace\iq\app\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.patchedRequire [as require] (D:\workspace\iq\app\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\workspace\iq\app\node_modules\notifme-sdk\lib\sender.js:43:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (D:\workspace\iq\app\node_modules\pirates\lib\index.js:99:24)
```

**Comment by sateesh2020** [comment]
Found that the issue is related to another library we used.

**Comment by BDav24** [comment]
@sateesh2020 FYI https://github.com/winstonjs/logform/pull/113 :)
